<center> Intro (in) intro 🤭

In [1]:
import torch

# View & Reshape

> view and reshape is method as simple u can "move" the data in shape that u want, the data still in same memory just the interpretation have been changed


In [3]:
x = torch.arange(12)
print(x)
print(x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [4]:
# from 1d vector we want change into 2d vector
y = x.view(3,4) 
print(y)
print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [ ]:
# u can also let torch automatically calculating the shape using -1
x = torch.randn(64, 3, 32, 32) # <= e.g. in image shape (BATCH, CHANNEL, HEIGHT, WIDTH)
# u wanna flattening into 2d
flat = x.view(x.shape[0],-1)
print(x.shape)
print(flat.shape)
# 3072 bcuz 3*32*32 = 3072

torch.Size([64, 3, 32, 32])
torch.Size([64, 3072])


In [ ]:
# and wut difference between view n reshape? reshape is more "safety" - if u cant share memory, it will automatically create copy
# so view() can only be use if tensor contigous in memory, if we want to permute/transpose first dont remember to call .contigous() 
x = torch.arange(20).view(5,4)
y = x.T # transpose <- non contigous
y.view(20) # surely error

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [9]:
# error fixing
x = torch.arange(20).view(5,4)
y = x.T.contiguous()
y.view(20) 

tensor([ 0,  4,  8, 12, 16,  1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7, 11,
        15, 19])

In [10]:
# so for simple approach, always using reshape() except u undstand about performs optimization & memory layout
x = torch.arange(20).view(5,4)
y = x.T
y.reshape(20)

tensor([ 0,  4,  8, 12, 16,  1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7, 11,
        15, 19])

# Permute n Transpose

> different from view & reshape which only change dimension "label", permute actually change the dimension sequence like we rotate coordinat axes

In [12]:
# btw its very crucial when we "playing" multimodal case due to each model have different sequence convension 
x = torch.randn(8, 224, 224, 3) # (B,H,W,C) 
# we want to new dimension => B,C,H,W
y = x.permute(0,3,1,2)
y.shape

torch.Size([8, 3, 224, 224])

In [ ]:
# transpose() quite different, it can only switch certain 2d
x = torch.randn(8,10,12) # RGB <-> switch into GBR
y = x.transpose(1,2,0)
y.shape

TypeError: transpose() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)


In [ ]:
# must be 2D! (dim1,dim2)
x = torch.randn(32, 768, 128) #(batch_size, seq_len, hidden_dim)
print(x.shape)
# we switch into (batch_size, hidden_dim, seq_len)
y = x.transpose(1,2)
print(y.shape)

torch.Size([32, 768, 128])
torch.Size([32, 128, 768])


# Unsquezee n squezee

> operation that ofen make error XD, both of them just deal with 1 dimension like adding or removing around ur tensor. This is crucial when broadcasting and when combining the outputs of two models.

In [19]:
x = torch.tensor([1, 2, 3])
print(x.shape)
# adding 1 => vector 2d
y = x.unsqueeze(1) # adding 1 dimension(cols)
print(y.shape)

torch.Size([3])
torch.Size([3, 1])


In [ ]:
x = torch.randn(1, 768, 128)
y = x.squeeze()
y.shape

torch.Size([768, 128])

In [23]:
# squeeze() without argument will remove all dim size-1. if batch_size=1, it can randomize shape! always specify dim yaa.
x = torch.randn(64,128,1)
y = x.squeeze(2)
y.shape

torch.Size([64, 128])